version: '3.8'

services:
  postgres:
    container_name: ms-subscription
    image: postgres:latest
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: subscription_rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ingress
      RABBITMQ_DEFAULT_PASS: ingress

volumes:
  postgres_data: