server:
  port: 2121

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subscriptions_db
    username: postgres
    password: pass

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_files: false
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml





